### ISSUE TITLE
leml initializer の実行タイミングを早くする

### ISSUE THREAD

**Issue by minoru-nagasaka-zeals** [onunu/leml#20]
## 事象
私たちの環境で以下のような事象が発生しました。
- rake assets:precompile を実施した際、以下のようなエラーが発生。
```
      01 RBENV_ROOT=/usr/local/rbenv RBENV_VERSION=2.4.1 /usr/local/rbenv/bin/rbenv exec bundle exec rake assets:precompile
      01 rake aborted!
      01
      01 NoMethodError: Cannot load `Rails.application.database_configuration`:
      01
      01 undefined method `[]' for nil:NilClass
      01
      01 (erb):5:in `<main>'
      01
      01 /opt/jupiter/shared/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/application/configuration.rb:133:in `database_configuration'
      01
      01 /opt/jupiter/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.1/lib/active_record/railtie.rb:121:in `block (2 levels) in <class:Railtie>'
```
該当箇所は以下。`application/configuration.rb`
``` application/configuration.rb
124       # Loads and returns the entire raw configuration of database from
125       # values stored in `config/database.yml`.
126       def database_configuration
127         path = paths["config/database"].existent.first
128         yaml = Pathname.new(path) if path
129 
130         config = if yaml && yaml.exist?
131           require "yaml"
132           require "erb"
133           YAML.load(ERB.new(yaml.read).result) || {}
134         elsif ENV["DATABASE_URL"]
135           # Value from ENV['DATABASE_URL'] is set to default database connection
136           # by Active Record.
137           {}
138         else
139           raise "Could not load database configuration. No such file - #{paths["config/database"].instance_variable_get(:@paths)}"
140         end
141 
142         config
143       rescue Psych::SyntaxError => e
144         raise "YAML syntax error occurred while parsing #{paths["config/database"].first}. " \
145               "Please note that YAML must be consistently indented using spaces. Tabs are not allowed. " \
146               "Error: #{e.message}"
147       rescue => e
148         raise e, "Cannot load `Rails.application.database_configuration`:\n#{e.message}", e.backtrace
149       end
```
133行目で database.yml を ERB で parse しているが、5行目で参照する Rails.application.secrets がnil であり、nill 参照で落ちていた。`database.yml`
``` database.yml
  1 default: &default
  2   adapter: mysql2
  3   encoding: utf8mb4
  4   pool: 5
  5   username: <%= ENV['DB_USERNAME'] || Rails.application.secrets.database[:username] %>
```

## 原因
Railtie#initializer において、`active_record.initialize_database`が実行される際、leml による secrets の初期化が完了していないことが直接の原因の模様。

initializer は、active_record.initialize_database 実行した後、leml.merge_secrets を実行している。
active_record.initialize_database を実行した際、database.yml を pase を試みて、secrets が存在しないため、nil 参照が発生。

### 補足
leml導入当初、このような事象は発生していませんでした。
その後、gem: delayed_job を導入した際、上述の事象が発生するようになりました。

## 要望
leml が secrets を初期化するタイミングについて、他の secrets を参照する initializer が動作するより、先に実行することは可能でしょうか。

**Comment by minoru-nagasaka-zeals** [comment]
ユーザー側での回避策がわかりました。
rails初期化イベントの `before_initialize` を使用することで、早いタイミング（bootstrap_hookの直後あたり）で leml が secrets を初期化するようになり、`active_record.initialize_database` での fail を回避できるようになりました。

config/application.rb
```
 19 module MyApp
 20   class Application < Rails::Application
 21     # Settings in config/environments/* take precedence over those specified here.
 22     # Application configuration should go into files in config/initializers
 23     # -- all .rb files in that directory are automatically loaded.
 : 
 : 
 33     config.before_initialize do
 34       require 'leml/core'
 35       Leml::Core.new.merge_secrets
 36     end
 37   end
 38 end
```
